include::header.adoc[]

:title: Assignment 3: Loops, I did it again! 
:Author Initials: ASN
:Date:    2020-02-07
:Revision: 0.1

= {title}

**Due Thursday, September 29, before midnight**

The goals of this assignment are:

* Work with loops
* Work with if statements
* Work with accumulator variables 

:stem: latexmath
:sectnums:

= Banner

Write a program, `Banner.java`, that draws an ascii border around a phrase given by the 
user.

Two examples of the running program are shown below. User input is shown in *bold*.

[source,subs="quotes"]
----
$ **java Banner**
Enter a phrase: **Welcome, Friends!**
Enter a decorator character: **+**
+++++++++++++++++++++
+ Welcome, Friends! +
+++++++++++++++++++++

$ **java Banner**
Enter a phrase: **Show me the money!**
Enter a decorator character: **$**
$$$$$$$$$$$$$$$$$$$$$$
$ Show me the money! $
$$$$$$$$$$$$$$$$$$$$$$
----

Hints and Requirements:

* Your border should fit around the entered phrase as in the examples. 

= Paper Fortune Teller

Whom will you marry? How many kids will you have? Back in the old days, we
turned to link:https://en.wikipedia.org/wiki/Paper_fortune_teller[paper fortune
tellers] to answer these along with many other burning questions about our
lives. 

Write a program, `FortuneTeller.java`, that implements a paper fortune teller. 
Your fortune teller should implement the following algorithm:

Below is an example

[source,subs="quotes"]
----
$ **java FortuneTeller**
----

Requirements and tips:

* 

= Poll predictor

_credit: Deepak Kumar_

Write a program, `Predictor.java`, which predicts a candidate's likelihood of
victory given its current polling number and margin of error. For example, if a
poll predicts that a candidate has a 47% chance of winning a state with a 6%
margin of error, can we make an overall prediction that the candidate will win
a state? 

One way to do this is to simulate an actual vote incorporating the margin of
error. Let's say, a poll (POLL) in a state shows that a candidate is likely to
receive 47% of the vote in their favor with a margin of error +/- 6% (MOE).
With this information, we can do a simulation of the state's voting, and arrive
at the % of votes received by the candidate in a poll:

[source]
----
SamplePoll = POLL + X * MOE
----

Where X is a number in the range [-1.0..1.0]. For example, if X is -0.5, then
the candidate will receive 0.47 + -0.5 * 0.06 = 0.44. This means, in this
instance, the candidate received only 44% of the votes (i.e. losing the state).
Alternately, if X turns out to be 0.8 then the candidate will receive 0.47 +
0.8 * 0.06 = 0.518 or 51.8% of the votes cast thereby winning the state.

We can use Java's Math.random() function to generate values of X in the range
[-1.0..1.0) and perform a simulation of several sample elections based on POLL
and MOE to see if a candidate is likely to win or lose a state. For example, 


[source,subs="quotes"]
----
$ **java-introcs Predictor Keystone 0.47 0.06 1000000**
Candidate win likelihood for Keystone state is 25.02% 
----

The above means that after performing 1 million randomized simulated polls based on POLL and MOE the candidate has a 25% likelihood of winning Keystone state. Here are some more examples.

[source,subs="quotes"]
----
$ **java-introcs Predictor Keystone 0.53 0.06 1000000**
Candidate win likelihood for Keystone state is 74.99%

$ **java-introcs Predictor Golden 0.49 0.07 1000000**
Candidate win likelihood for Golden state is 42.82%

$ **java-introcs Predictor Nutmeg 0.51 0.02 1000000**
Candidate win likelihood for Nutmeg state is 75.01%
----

You program, `Predictor.java`, should take the following command line arguments:

* `state`: (String) state name. For example, Keystone, Golden, or Nutmeg
* `POLL`: (double) polling number, a double in the range [0,1]. For example, 0.53, 0.49, or 0.51
* `MOE`: (double) margin of error, a double in range [0,1]. For example, 0.06, 0.07, or 0.02 
* `N`: (int) number of simulation iterations. For example, 1000000

Your program, `Predictor.java`, should implement the following algorithm

[source]
----
wins = 0
Repeat N times
   Compute SamplePoll = POLL + randomNumber * MOE
   If SamplePoll > 0.5 then
       Increment wins by 1
   Compute and output overall win likelihood = (wins/N)
----

.Poll data
|===
| STATE | Poll | Margin of Error 
| Garden | 48% |  3% 
| Empire | 53% |  4% 
| Nutmeg | 42% | 9% 
| Golden | 52% |  4% 
| LoneStar | 49% | 5% 
|===

In your writeup, include the likelihoods computed by your program for all states, using 
N = 1000000.

NOTE: Pretty printing is implemented using `StdOut.printf` as described in section 1.5 of your textbook. Using `printf` requires that you compile with the command `javac-introcs` and run with the command `java-introcs`.

= What to hand-in

. The programs, `Banner.java`, `FortuneTeller.java`, `Predictor.java`.
. Make sure each program has a header containing your name, date, and purpose of the program
. A brief write-up containing your name, assignment number, and a few sentences about how long you 
spent on the assignment and any interesting bugs you solved. *Don't forget to include the likelihoods 
computed by your Predictor!* 

== How to hand-in

. Copy your programs and writeup to your dropbox, into the folder called `A03`. 
