include::header.adoc[]
//override default to include table css
:stylesheet: front.css
:leveloffset: -1

:course: CS 113
:title: Computer Science I
:term: Fall 2022

= {course}: {title} -- {term}

[.anns]
== Announcements

* You can install Java on your own laptop! link:develEnvSetup.html[See here for instructions].
* link:asst06.html[Assignment 6] has been posted: *Due October 27th*
* Current week notes: link:#week08[Week 08]

== **Schedule**

The syllabus may change during the semester. Please check here every week for updates 
on lecture content, worksheets, and assignments.

include::schedule.adoc[]

== Course Info

**Welcome to CS113**, an introduction to computer science. This class covers 
the basics of computer programming using Java. Students will learn 
fundamental programming concepts, such as variables, conditional statements, 
loops, functions, and classes. Students will develop their ability to write 
programs to solve a variety of problems, read existing programs, 
and find and fix errors in existing code. 

No prior computer programming experience is necessary or expected for this
class. If you have never programmed, or don't know much about computers, this
class is for YOU! However, we do ask students to have "quantitative readiness
(QA)". In this course, QA means a willingness to confront equations and
concepts with curiosity. Students may need to do additional learning outside
of class if they encounter mathematical concepts to which they do not have
previous exposure.

Computer programmers must mix systematic thinking with creativity. Programming 
can be time-consuming and difficult work, but the results are rewarding!  

_This course is appropriate for all students who want to learn how to read, write, 
and debug computer programs as well as learn solve problems like a computer scientist_. 

=== Meeting Times

[.center,options="header,autowidth"]
|===
| Activity | Location | Time

| Lecture (Section 1 - Normoyle) | Park 338 | MW 1:10-2:30pm EST
| Lecture (Section 2 - Poliak) | Park 300 | TTH 12:55-2:15pm EST
| Lab A (Poliak) | Park 230 | Tuesday, 2:25 PM- 3:15 PM EST
| Lab B (Poliak) | Park 230 | Thursday, 11:55 AM-12:45 PM EST
| Lab C (Normoyle) |  Park 231 | Wednesday, 2:40 PM- 4:00 PM EST
| Office Hours (Normoyle) | Park 200B | Wednesday, 4-5 PM EST, Thursday afternoons (By appointment)   
| Office Hours (Poliak) | Park 200C |  Wednesday, 10:30-11:30am EST
| TA Office Hours | Park 231 |  Sunday-Thursday, 6-10 PM EST

|===

=== TA Office Hours 

All TA office hours will be in person in the computer science labs (*Park 231*) in the Park
Science Center. TA office hours will be in the evenings, Sun-Thurs 6-10pm 

== Text and Software

*  **Introduction to Programming in Java (Second Edition)** by Robert Sedgewick & Kevin Wayne. Addison-Wesley 2017. Available in Campus Bookstore, or purchase online from Amazon.com (Price on August 19, 2020 is $35.99 for e-text, $65.00 paperback). Book's companion website: Click here.
*  **Dropbox Account** Please go to link:https://dropbox.com/[dropbox.com] and register. You will be using dropbox to submit assignments. 
*  **Slack** Please go to link:https://slack.com/signin[slack.com]. Our workspace is BrynMawr-CS110-F22. You can ask questions and request one-on-one help over zoom using this course's slack channel. 
*  **Development environment** This refers to the tools we will use to write and run code. We will distribute an installer to help you set this up. We will use git bash, OpenJDK-11, and Visual Studio Code (VS Code).

*Resources*

* link:develEnvSetup.html[Instructions for setting up Java on your own laptop]
* link:https://github.com/BrynMawr-CS113-F22/class-examples-normoyle[JAVA programs from Professor Normoyle's lectures]
* link:https://github.com/BrynMawr-CS113-F22/class-examples-poliak[JAVA programs from Professor Poliak's lectures]

== Grading Policies

All graded work will receive a grade, 4.0, 3.7, 3.3, 3.0, 2.7, 2.3, 2.0, 1.7,
1.3, 1.0, or 0.0. At the end of the semester, final grades will be calculated
as a weighted average of all grades according to the following weights:

|===
| 35% | Final Exam
| 35% | Assignments
| 30% | Labs
|  5% | Participation 
|===

include::quizzes.adoc[]

//include::labPolicy.adoc[]

include::latePolicy.adoc[]

include::integrity.adoc[]

include::accomodations.adoc[]

include::covidpolicy.adoc[]

== External Links

Links that are related to the course may be posted here. If you have suggestions for links, let us know.

[unstyled]
 * link:http://www.dropbox.com/[Dropbox]
 * link:https://www.brynmawr.edu/academicsupport/academic-and-student-support-services[Academic Support, including help with math and quantitative skills!]
 * This site was generated with link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[asciidoctor]
